// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _DefaultCellDDL_H_
#define _DefaultCellDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "DefaultCellParameter.h"
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class DefaultCell;

class DOCLASS(DefaultCell): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(DefaultCell);

	DataSetTemplate<DefaultCellParameter>	m_dsParam;
};

class _DOC_DefaultCell: public DOClassTemplate<DOCLASS(DefaultCell), _DOC_GlobalDO, DOCLASSID(DefaultCell)> {
public:
	_DOC_DeclareGeneralMethods(DefaultCell)
};

#endif // _DefaultCellDDL_H_
