// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _DefaultCellParameterDDL_H_
#define _DefaultCellParameterDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(DefaultCellParameter): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(int,m_idDupSpace);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_idDupSpace);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_idDupSpace);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _DefaultCellParameterDDL_H_
