//  
//   (c) Copyright 1998-2001, Quazal
//   ALL RIGHTS RESERVED
//  
//  


#ifndef _DOClassID_H_
#define _DOClassID_H_

// System reserved DOClassIDs:

#define INVALID_CLASSID				0
#define DuplicatedObject_ClassID	1
#define FIRST_CORE_DOCLASSID		2

// Group = Miscellaneous Types and Macros

/*
Summary: A DOClassID is used to identify a DOClass.

Remarks: A DOClassID is automatically generated by the DDL compiler. For example,
if the following is defined in the DDF file:

         define CustomSessionObject;

The DDL compiler will generate the DOClassID. It can be accessed via the DOCLASSID
macro as follows:

         DOCLASSID(CustomSessionObject)     
      
See Also:  DDF File Syntax, DDL File Syntax, Duplicated Object Overview, DOCLASSID
*/
typedef unsigned long DOClassID;

#endif
