// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _DOCoreDDF_H_
#define _DOCoreDDF_H_

#include <ObjDup/ObjDupExport.h>
#define DOLoadBalancing_ClassID FIRST_CORE_DOCLASSID+11
#define DefaultCell_ClassID FIRST_CORE_DOCLASSID+7
#define GlobalDO_ClassID FIRST_CORE_DOCLASSID+1
#define IDFactory_ClassID FIRST_CORE_DOCLASSID+8
#define LoadBalancingDomain_ClassID FIRST_CORE_DOCLASSID+10
#define MulticastGroup_ClassID FIRST_CORE_DOCLASSID+6
#define MulticastGroupLoadBalancing_ClassID FIRST_CORE_DOCLASSID+12
#define PromotionReferee_ClassID FIRST_CORE_DOCLASSID+9
#define RootDO_ClassID FIRST_CORE_DOCLASSID+0
#define SecondaryStation_ClassID FIRST_CORE_DOCLASSID+3
#define Session_ClassID FIRST_CORE_DOCLASSID+5
#define SessionClock_ClassID FIRST_CORE_DOCLASSID+4
#define Station_ClassID FIRST_CORE_DOCLASSID+2
#define FIRST_USER_DOCLASSID FIRST_CORE_DOCLASSID+13
extern WKHandle g_hDOLoadBalancing;
extern WKHandle g_hMulticastGroupLoadBalancing;
extern WKHandle g_hdoPromotionReferee;
extern WKHandle g_hdoSession;
extern WKHandle g_hdoSessionClock;

#endif // _DOCoreDDF_H_
