// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _DOHandleVectorDDL_H_
#define _DOHandleVectorDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(DOHandleVector): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VECTOR(DOHandle,m_vhMembers);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_OBJECT(m_vhMembers, bDiscovery);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_OBJECT(m_vhMembers);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _DOHandleVectorDDL_H_
