// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _DOLoadBalancingDDL_H_
#define _DOLoadBalancingDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "LoadBalancingDomain.h"
#include "DOCoreDDF.h"

class DOLoadBalancing;

class DOCLASS(DOLoadBalancing): public LoadBalancingDomain {
public:
	_DO_DeclareGeneralMethods(DOLoadBalancing);

};

class _DOC_DOLoadBalancing: public DOClassTemplate<DOCLASS(DOLoadBalancing), _DOC_LoadBalancingDomain, DOCLASSID(DOLoadBalancing)> {
public:
	_DOC_DeclareGeneralMethods(DOLoadBalancing)
};

#endif // _DOLoadBalancingDDL_H_
