//  
//   (c) Copyright 1998-2001, Quazal
//   ALL RIGHTS RESERVED
//  
//  

#ifndef _DuplicatedObject_H_
#define _DuplicatedObject_H_

#include <ObjDup/ObjDupDecl.h>
#include <ObjDup/RefTemplate.h>
#include <ObjDup/SelectionIteratorTemplate.h>
#include <ObjDup/MethodID.h>
#include <ObjDup/DuplicationSpace.h>
#include <ObjDup/DuplicationSpaceTable.h>
#include <ObjDup/DOSBP.h>
#include <ObjDup/CollectionItem.h>
#include <ObjDup/MemberContainer.h>
#include <ObjDup/DuplicatedObjectStore.h>
class MulticastControl;
class DuplicatedObjectStore;
class DOClass;
class DataSet;
class DataSetOperation;
class DiscoveryMecanism;
class ObjDupProtocol;
class DOOperation;
class PromotionReferee;
class FetchContext;
class MigrationContext;
class CallContext;

//group=DDL Output

/*
Description: Use this macro to generate the name of the base class from
which your own duplicated object implementation inherits.
Remarks:
$ifdef NETZ$

For example, lets say a duplicated object is declared like this in a DDL file :

      doclass GameObject {
          // DDL declarations
      };

The user-defined /GameObject/ class is declared like this :

      class GameObject : public DOCLASS(GameObject)  {
          // User specific variables and methods
      };

$endif$

$ifdef TSIS$

For example, lets say a duplicated object is declared like this in a DDL file :

      doclass SessionObject {
          // DDL declarations
      };

The user-defined /SessionObject/ class is declared like this :

      class SessionObject : public DOCLASS(SessionObject) {
          // User specific variables and methods
      };

$endif$
*/
#define DOCLASS(C) _DO_##C

/*
Description: The class DuplicatedObject is the root of all user-defined duplicated
objects.  If a DOClass is defined in the DDL, the corresponding
DOClass generated by the DDL compiler will ultimately inherit from the
DuplicatedObject class.
Remarks: The DuplicatedObject class contains regular methods, inherited by
every user doclass.  It also defines system callbacks.  The system
callbacks have the semantic of a virtual method.  If they are
overriden by the user doclass, the overriden method will be called
whenever applicable.
See Also: Actions Overview, Fault Tolerance Overview, Load Balancing Overview
*/
class DuplicatedObject: public CollectionItem {
	//group=
	public:
		/*
		Summary: Instantiates a duplicated object.
		Remarks: Duplicated objects should never be directly instantiated.  Instead use 
		DuplicatedObject::Create.
		*/
		DuplicatedObject();
		/*
		Summary: Destroys the duplicated object.
		Remarks: The correct way to destroy a duplicated object is via the method 
		DuplicatedObject::DeleteMainRef. When a duplicated object is destroyed the datasets and 
		well-known handles associated to it are also destroyed. The duplicated object destructor 
		has the semantics of a virtual method and therefore, it can be rewritten in a user subclass.

Note: The duplicated object destructor will not be called on an object until all references 
to the object have be deleted.

		See Also: DataSet, WKHandle, DeleteMainRef
		*/
		~DuplicatedObject();

		/*
		Summary: Returns a DOHandle to the duplicated object that refers to the local instance 
		of the duplicated object. 
		Returns: The DOHandle to the duplicated object or INVALID_DOHANDLE if the call signalled 
		an error. The error SYSTEMERROR_GEN_INVALID_OPERATION is possible.
		See also: GetHandleValue
		*/
		DOHandle GetHandle() const;

		/*
		Summary: Returns a ulong that represents the duplicated object instance.
		Returns: A ulong that represents the duplicated object or INVALID_DOHANDLE if the call 
		signalled an error. The error SYSTEMERROR_GEN_INVALID_OPERATION is possible.
		See also: GetHandle
		*/
		unsigned long GetHandleValue() const {return GetHandle();}

		// {secret}
		DOHandle _GetHandle() const;
		// {Secret}
		void SetClassID(unsigned long ulClassID) {m_dohMyself.SetClassID(ulClassID);}
		// {Secret}
		void SetObjectID(unsigned long ulObjectID) {m_dohMyself.SetObjectID(ulObjectID);}
		// {Secret}
		void AcquireObjectID();
		// {Secret}
		void SetHandle(DOHandle hNewHandle) {m_dohMyself=hNewHandle;}

		/*
		Summary: The method is used to determin if an object is duplicated all over the session and if it
		is using broadcast to update itself.
		Remarks: This method must be called on the Duplication master of an object. The method returns immediately 
		before ensuring successful migration or encountering a system error.  
		If a fault occurs on the destination station then migration will not proceed.
		Returns: The method returns true if the object is a Well-known duplicated object or Global
		duplicated object, false if not.
		*/		
		bool UsesBroadcast() const;

		/*
		Description: This method returns the class name of the DuplicatedObject as a string.
		Returns: A string that represents the class name of the DuplicatedObject.
		Remarks: Use this method to get the class name of the duplicated object instance as a string.
		For example,
		
        double DuplicatedObject::ComputeDistance(DuplicatedObject * pObservedDuplicatedObject){
             _tprintf(_T("Computing distance for Duplicated Object of class %s"),  pObservedDuplicatedObject->GetClassNameString());
             [...]
        }
		*/
		const TCHAR* GetClassNameString() const;

		/*
		Summary: Returns the DOClassID of the duplicated object.
		This ID is generated by the DDL compiler.
		See also: DOCLASSID
		*/
		DOClassID GetClassID() const;

		/*
		Summary: Returns whether or not a DuplicatedObject instance is an instance
		of a specified doclass.

		Parameters:
		idDOCID:  the DOClassID of the DuplicatedObject.

		Returns: true if the DuplicatedObject instance has this DOClassID, false if otherwise.
		Remarks: Use the DOCLASSID	macro to retrieve the DOClassID for a given DOClass. For example:

						NamedObject::SelectionIterator  itNamedObject; 
						itNamedObject.GotoStart(); 
						while(! (itNamedObject.EndReached())){ 
											 if (ItNamedObject->IsA(DOCLASSID($AvatarORInformationObject$))){
													   itNamedObject++;
												}
						}                       
                  
		See Also: IsAKindOf
		*/
		bool IsA(DOClassID idDOCID) const;
		
		/*
		Summary: Returns whether or not a DuplicatedObject instance is an instance or
		a descendant of the specified DOCLASS.

		Parameters:
		idDOCID: the DOClassID of the DuplicatedObject.

		Returns: true if the DuplicatedObject instance is an instance of or a descendant class 
		of this DOClassID, false if otherwise.
		Remarks: Use the DOCLASSID macro to get an instance of this class.  For example:

						NamedObject::SelectionIterator  itNamedObject; 
						itNamedObject.GotoStart(); 
						while(! (itNamedObject.EndReached())){ 
											 if (ItNamedObject->IsAKindOf(DOCLASSID($AvatarORInformationObject$))){
													   itNamedObject++;
												}
						}                        
              
		See Also: IsA
		*/
		bool IsAKindOf(DOClassID idDOCID) const;

		// {Secret}
		unsigned long GetObjectID() {return m_dohMyself.GetObjectID();}

/*
Summary: Propagates the contents of all the duplicated object
datasets to its duplicas, or if a parameter is supplied it propagates only
the contents of the specified dataset.

Parameters:  
refDataset:  An optional pointer to the specific dataset that is to be updated.  

Remarks:  This method must be called on a Duplication master.  It has the
semantic of a virtual method: it can be called on a base class and
all the derived class datasets will also be updated.  The call can be made
with or without the parameter to specify which of the duplicated object's datasets should
be updated. For example, suppose we have a Position dataset and the m_dsPosition dataset
member of type Position is associated with the Sphere doclass in the DDL file, then it
is possible to update just that Position dataset as follows:

      //assuming that all we have is a pointer to our Sphere duplicated object
      poSphere->Update(poSphere->m_dsPosition);

If a station cannot directly communicate with a station to which it wishes to send a message
$PRODUCTNAME$ will automatically route the message via another station. This effectively deals with 
the problem of stations being unable to communicate with each other due to the fact that they 
have no common transport type.

Note: Depending on the dataset update policy, Update does not necessary
generate a network message. If some of the datasets are extrapolated, Update must be called
regularly (i.e. after DoPhysic)  even if the contents of the datasets did not change. This
is necessary to maintain a coherent prediction model for the
extrapolated datasets.

Returns: true if the update call is successful, false if it signals an error. If this method is 
called on a Duplica the error SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA will be returned.
SYSTEMERROR_MISSING_DATASET_CALLBACK is also possible.
*/
		bool Update();
		bool Update(DataSet& refDataset);
		
		/*
		Summary: Uses the content of the buffer to refresh the
		variables of all or a specified buffered dataset of a Duplica.

		Parameters:
		refDataset: An optional pointer to the dataset that is to be refreshed.

		Remarks:  This method must be called on the buffered datasets of a Duplica to
		refresh the value of the dataset variables. If an extrapolation filter
		is used, this method will refresh the dataset variables with an
		extrapolation of their value. This method is only valid for the buffered datasets 
		of a Duplica.

		Returns: true if the method is successful and false if it signals an error. The error 
		SYSTEMERROR_GEN_INVALID_OPERATION will be returned if the dataset is not buffered.  
		SYSTEMERROR_OBJDUP_INVALID_ON_MASTER can also be signalled.
		*/
		bool Refresh();
		bool Refresh(DataSet& refDataset);

		//{secret}
		void ExtractADataSet(Message* pMsg);
		//{secret}
		void Initialize(Message* pMsg);

		/**********
		 *
		 * Callbacks.
		 *
		 **********/

		//{secret}
		bool CallApproveFaultRecovery();
		//{secret}
		bool CallApproveEmigration(unsigned long ulReason);
		//{secret}
		void CallInitDO();
		//{secret}
		double CallComputeDistance(DuplicatedObject* pObservedDuplicatedObject);
		//{secret}
		void CallOperationBegin(DOOperation* pOperation);
		//{secret}
		void CallOperationEnd(DOOperation* pOperation);
		//{secret}
		void CallDataSetOperationBegin(DataSetOperation* pOperation);
		//{secret}
		void CallDataSetOperationEnd(DataSetOperation* pOperation);
		//{secret}
		unsigned long CallMsgSendingCapacity(unsigned long ulNbStations);		
		//{secret}
		double CallGetWeight();
		//{secret}
		void CallTrace(unsigned long ulTraceFlag=TRACE_ALWAYS);

		/**********
		 *
		 * Default callback implementation...
		 *
		 **********/

		/*
{Group:System Callbacks}

Summary: This method returns whether or not a duplicated object
accepts to become a Duplication master after the station that controlled
it has failed.

Remarks: The following code shows implementation of the ApproveFaultRecovery 
system callback, which dictates that $AvatarORInformationObject$ objects are fault-tolerant:

      class $AvatarORInformationObject$ : Public DOCLASS($AvatarORInformationObject$) {
          public:
			$AvatarORInformationObject$();
			~$AvatarORInformationObject$();
			bool ApproveFaultRecovery() {
				return true;
			}
			//other application specific methods and variables
	   };
	   
Note: By default, if the $gameORapp$ does not implement this system callback, 
fault recovery is disabled for the given DOClass.

Returns: If ApproveFaultRecovery returns true, a new host can and does become the new 
Duplication master and gains control of the duplicated object. Otherwise, the 
duplicated object is destroyed by $PRODUCTNAME$.
See Also: Fault Tolerance Overview, ApproveEmigration
*/
		bool ApproveFaultRecovery();
		
/*
{Group:System Callbacks}

Summary: This system callback is called by $PRODUCTNAME$ to determine if a duplicated object
allows Emigration.

Parameters:

ulReason: The reason for which an emigration is requested.  The values are one of
MIGRATION_REASON_LEAVING_$GAMEORCLUSTER$, MIGRATION_REASON_LOAD_BALANCING.

Remarks: The following code shows implementation of the ApproveEmigration 
system callback, which dictates that $AvatarORInformationObject$ objects can migrate:

      class $AvatarORInformationObject$ : Public DOCLASS($AvatarORInformationObject$) {
          public:
			$AvatarORInformationObject$();
			~$AvatarORInformationObject$();
			bool ApproveEmigration(unsigned long ulReason) {
				return true;
			}
			//other application specific methods and variables
	   };

      
Note: By default, if the class does not implement this system callback emigration
is disabled for the given DOClass.

See Also: Fault Tolerance Overview, Load Balancing Overview, RemoveFromStoreOperation, ApproveFaultRecovery
*/
		bool ApproveEmigration(unsigned long ulReason);
		
/*
{Group:System Callbacks}

Summary: Called by the system when the duplicated object has been
initialized.

Remarks: When InitDO is called, the Duplication role of the
DuplicatedObject is fully defined.  If it is a Duplica, all its
datasets have been appropriately initialized.

This section explains how to use the InitDO system callback.

Suppose we want to create a $gameORapp$ where $AvatarORInformationObject$s appear at random
locations.  We also want to render the graphical representation of the
$AvatarORInformationObject$s at the same location in 3D space on all the stations
immediately when they join the session.

Lets say the object '$AvatarORInformationObject$' contains a position dataset defined in the DDL file as follows:

      dataset Position {
	      double x;
	      double y;
	      double z;
      };

When creating an $AvatarORInformationObject$ via DuplicatedObject::Create, a Duplication
master is created, so all we need to do before rendering it is set the
values of its position dataset. When the $AvatarORInformationObject$ is published (via
DuplicatedObject::Publish), its Duplica appear on all the stations that require a copy of the object
which then need to be rendered at the correct position.  Thus, setting the
$AvatarORInformationObject$ position from within the InitDO function would be done as follows:

      void $AvatarORInformationObject$::InitDO(void) {
          if ( IsADuplicationMaster() )
          {
              Position.x = SomeRandomValue();
              Position.y = SomeRandomValue();
              Position.z = SomeRandomValue();
          }

          RenderAtCurrentPosition();
      }

Note: For this example, because the datasets have default values when
the $AvatarORInformationObject$ object is instantiated, setting the $AvatarORInformationObject$ position from
within the constructor will _not_ work.

See Also: DuplicatedObject::Create, DuplicatedObject::Publish, IsADuplicationMaster, IsADuplica
*/
		void InitDO();
		
/*
{Group:System Callbacks}

Summary: Called by the system to determine the distance between two
duplicated objects.

Parameters:
pObservedDuplicatedObject: pointer to the duplicated object which you want to compute the
distance to.  

Remarks: When distance-based dead reckoning is invoked, the desired precision of the extrapolation 
depends on a distance between the duplicated objects. The distance is a value 
specific to the $gameORapp$ computed via this system callback and is typically the distance
between the position of the objects in the virtual world.

For distance-based dead reckoning $PRODUCTNAME$ needs to compute the distance
between the registered observer (register via Station::RegisterObserver
and get via Station::GetObserver) and the Duplica of the 
object for which it is doing the distance-based dead reckoning.  Thus, $PRODUCTNAME$
calls this method on the Duplica of the observer and passes to the function a pointer 
to the duplicated object for which it is determining the allowable error in the
extrapolation. The distance must be a positive value, or the special value
UNKNOWN_DISTANCE. The default implementation returns UNKNOWN_DISTANCE.

The following is an example that computes the distance between two
Spheres in a virtual world.  The context of this example is found in the
Dead Reckoning Overview.

			double Sphere::ComputeDistance(DuplicatedObject * pObservedDuplicatedObject) {
				switch (pObservedDuplicatedObject->GetClassID()) {
					case DOCLASSID (Sphere):
						return sqrt( sqr(m_Pos.x-((Sphere*)pObservedDuplicatedObject)->m_Pos.x)
									 +sqr(m_Pos.y-((Sphere*)pObservedDuplicatedObject)->m_Pos.y));
					default:
						return UNKNOWN_DISTANCE ;
				}
			}

See Also: Dead Reckoning, Dead Reckoning Overview, ErrorToleranceFunction, UNKNOWN_DISTANCE, 
Station::RegisterObserver, PHBDRParameters
*/
		double ComputeDistance(DuplicatedObject* pObservedDuplicatedObject);
		
		/*
{Group:System Callbacks}

		Description: Called by $PRODUCTNAME$ each time a duplicated object operation begins.
		Remarks: This method is called at the beginning of a DOOperation with a reference to 
		the DOOperation that just began as a parameter.  Switch this parameter to find out what 
		type of operation it is and then implement your functionality. See 
		DuplicatedObject::OperationEnd for an example of the implementation of this method.
		See Also:  System Operations, OperationEnd
		*/
		void OperationBegin(DOOperation* pOperation);
		
		/*
{Group:System Callbacks}

		Description: Called by $PRODUCTNAME$ each time a duplicated object operation ends.
		Remarks: This method is called at the end of a DOOperation with a reference to the DOOperation 
		that just terminated as a parameter.  Switch this parameter to find out what type of operation 
		it is and to implement your functionality. The following is an example to capture the DOOperation 
		RoleChangeOperation. Thus, each time an AISphere object is locally promoted to the 
		role of Duplication master, either due to Load Balancing or fault recovery, the local station will 
		take over the control of its AI.

				void AISphere::OperationEnd(DOOperation* pOperation) {
					switch (pOperation->GetType()) {
						case Operation::RoleChange:
								if ( ((RoleChangeOperation*) pOperation)->IsAPromotion()){
									//Take Over control of AI
								}
						break;
					}
				}

		See Also: System Operations, OperationBegin
		*/
		void OperationEnd(DOOperation* pOperation);

		/*
{Group:System Callbacks}

		Description: Called by $PRODUCTNAME$ each time a dataset operation called on a duplicated object begins.
		Remarks: This method is called at the beginning of a DataSetOperation with a reference to 
		the DataSetOperation that just began as a parameter. Switch this parameter to find out what 
		type of operation it is and then implement your functionality.
		See Also:  System Operations, DataSetOperationEnd
		*/
		void DataSetOperationBegin(DataSetOperation* pOperation);
	
		/*
{Group:System Callbacks}

		Description: Called by $PRODUCTNAME$ each time a dataset operation called on a duplicated object ends.
		Remarks: This method is called at the end of a DataSetOperation with a reference to the DataSetOperation 
		that just terminated as a parameter. Switch this parameter to find out what type of operation 
		it is and to implement your functionality.
		See Also: System Operations, DataSetOperationBegin
		*/
		void DataSetOperationEnd(DataSetOperation* pOperation);

		/*
		Description: Sets the default message sending capacity of a particular duplicated object.
		Remarks: The message sending capacity of a duplicated object is the maximum number of duplicas
		that a Duplication master will send an update message to directly. This quantity is set for 
		a particular duplicated object. For example, if the MsgSendingCapacity is set to 10, a duplication
		master will send update messages directly to 10 duplicas. If there are more than 10 duplicas that 
		the master needs to update, then 9 messages will be sent directly to the duplicas and 1 message to the 
		RootMulticastGroup which will then forward the messsage via the multicast group hierarchy to
		all the other duplicas.
		
Note: The message sending capacity must be equal to or greater than 1.
        
		See Also: MulticastPolicy, MulticastPolicy::SetDefaultMsgSendingCapacity
        */
		unsigned long MsgSendingCapacity(unsigned long ulNbStations);

		//{secret}
		double GetWeight() {return 0.0;}

		/*
		Description: Traces the default information for a duplicated object instance.
		Remarks: The default trace information for a duplicated object consists of its class name, 
		DOHandle, Duplication role (i.e. Duplica or Duplication master), its ref count (i.e. how many
		DORefs are presently created in the system for this object), whether or not
		it is flagged for destruction, as well as the station on which its Duplication master instance resides.
	 	Redefine the Trace method in the implementation of your DOCLASS in order to
	 	trace $gameORapp$ specific information to that particular DOCLASS.
	 	However, in order to continue to trace the default information, ensure to include a call to
	 	DOCLASS(YourDOCLASS)::Trace(). For example:
	 	
	 	          class Room:DOCLASS(Room){
	 	          	[...]
	 	          	void Trace(unsigned long ulTraceFlag) {
	 	          		DOCLASS(Room)::Trace(ulTraceFlag);
	 	          		TRACE(ulTraceFlag, _T("Room number is %d"), GetRoomNumber());
	 	          	}	
	 	          	[...]	
	 	          };	
		
		See Also: DuplicatedObjectStore::Trace, System Traces, TraceOutput
		*/
		void Trace(unsigned long ulTraceFlag=TRACE_ALWAYS);


		// Discovery related methods...
		// {Secret}
		void SpecificAddDSToDiscoveryMessage(Message* pMsg) {}; 
		// {Secret}
		void SpecificExtractDSFromDiscoveryMessage(Message* pMsg) {}; 
		// {Secret}
		bool SpecificRefresh(DuplicatedObject *pDO, DataSet *pDataset = NULL) {return false;}
		// {Secret}
		bool SpecificExtractADataset(Message* pMsg, unsigned char byDatasetIndex);
		// {Secret}
		bool SpecificUpdate(DataSet *pDataset = NULL) {return false;}
		// {Secret}
		void FillDupSpaceInfo(DuplicationSpace::Role eRole, DupSpaceID* pArray, unsigned int* puiIndex){}

		// Methods related to action calls.
		//{secret}
		Message* CreateStubMessage(MethodID* pidMethod);
		//{secret}
		bool SendStubMessage(bool bSendToDuplicas, Message* pMsg);
		//{secret}
		void MulticastMessage(Message* pMsg, bool bReliable=true);
		void MulticastMessage(Message* pMsg, MulticastControl* pControl, bool bReliable=true);
		// {Secret}
		int GetNbDupSpaces(DuplicationSpace::Role eRole);
		// {Secret}
		void FillDupSpacesArray(DuplicationSpace::Role eRole, 
								DupSpaceID* pArray);


		/**********
		 *
		 * DOMessaging methods.
		 *
		 **********/
		
		// {Secret}
		bool CallProcessDOMessage(Message *pMsg);
		// {Secret}
		bool ProcessDOMessage(Message *pMsg);
		//{secret}
		Message* CreateDOMessage(DOHandle hDODest);
		// {Secret}
		Message* DuplicatedObject::CreateDOMessageForSelf();
		//{secret}
		bool SendDOMessage(Message *pMsg, DOHandle hStation, bool bReliable=true);
		// {Secret}
		bool SendDOMessageToMaster(Message *pMsg, bool bReliable=true);

		/**********
		 *
		 * Fetch/CreateDuplica methods
		 *
		 **********/
		
		/*
		Description: Use this method to create a Duplica of a given duplicated object.
		Parameters:
		hNewDuplicaStation: The DOHandle of the station on which a Duplica will be created. 
		
		Remarks: This method is one manner in which to create a Duplica of an object on a station. 
		The method must be called on a Duplication master to create a Duplica of itself.
		See Also: FetchDuplica
		*/
		bool CreateDuplica(DOHandle hNewDuplicaStation);
		
		/*
		Description: Use this method to fetch a Duplica of a given duplicated object.
		Parameters:
		hFetchedObject: The DOHandle of the fetched object.
		pContext: A pointer to the FetchContext.
		
		Remarks: This method is one manner in which to create a Duplica of an object on a station.
		See Also: CreateDuplica, FetchContext
		*/ 
		static bool FetchDuplica(FetchContext* pContext, DOHandle hFetchedObject);
		
		/*
		Description: Use this method to determine if a given object is in the process of being fetched.
		Parameters:
		hTargetStation: The DOHandle of the TargetStation from which the Duplica will be fetched.
		hFetchedObject: The DOHandle of the fetched object.
		
		Returns: true if the specified object is in the process of being fetched from the target
		station (if specified), false if it is not.
		*/ 
		static bool FetchInProgress(DOHandle hFetchedObject);
		static bool FetchInProgress(DOHandle hFetchedObject, DOHandle hTargetStation);


		/**********
		 *
		 * FaultRecovery methods.
		 *
		 **********/

		// {secret}
		void PerformFaultRecovery(PromotionReferee* pReferee);

		/**********
		 *
		 * Migration methods
		 *
		 **********/

		/*
		Description: Use this method to emigrate a duplicated object to a specific station.

		Parameters:
		idNewLocation: The StationID to which the duplicated object will emigrate (i.e. the destination
		StationID for the duplicated object).
		pContext: A pointer to the MigrationContext.
		hTargetStation: The DOHandle of the TargetStation to which the object will migrate.

		Remarks:  This method must be called on the Duplication master.  The method locks
		until the emigration completes or the error SYSTEMERROR_OBJDUP_CANNOT_EMIGRATE is generated
		due to the unavailability of station idNewLocation.

Note: Alternatively, you may use the method AttemptEmigration, which returns immediately but 
does not guarantee a successful emigration. 

		Returns: true if the method is successful and false if the method signals an error.
		SYSTEMERROR_OBJDUP_CANNOT_EMIGRATE, and 
		SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA can be signalled by this call.
		
		See Also: AttemptEmigration, MigrationInProgress
		*/
		bool Emigrate(StationID idNewLocation);
		bool Emigrate(MigrationContext* pContext, DOHandle hTargetStation);
		
		//Description: Use this method to determine if the migration of an object is in progress.
		//Returns: true if the object is in the process of migrating, false if it is not.
		//See Also: Emigrate, AttemptEmigration
		bool MigrationInProgress();

		/*
		Summary: The method attempts to emigrate a duplicated object to a specified station.

		Parameters:
		idNewLocation: The StationID to where the duplicated object will attempt to emigrate (i.e. the destination
		StationID for the duplicated object).
		hNewLocation: The DOHandle of the station to where the duplicated object will attempt to emigrate.

		Remarks:  This method must be called on the Duplication master of an object. The method returns immediately 
		before ensuring successful migration or encountering a system error.  
		If a fault occurs on the destination machine then migration will not proceed.

Note: Alternatively, you may use the method Emigrate, which locks until the emigration process 
is successful or an error is generated.

		Returns: The method returns true if successful or false if it signals an error.  
		SYSTEMERROR_OBJDUP_CANNOT_EMIGRATE, SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA can both
		be signalled by this call.  
		See Also: Emigrate, MigrationInProgress
		*/		
		bool AttemptEmigration(StationID idNewLocation);
		bool AttemptEmigration(DOHandle hNewLocation);

		// {secret}
		void PrepareToLeave();
		//{secret}
		bool PerformMigration(DOHandle hOldStation, DOHandle hNewStation);
		//{secret}
		DOHandle SelectNewLocation(unsigned long ulReason);

		// Misc methods...
		//{secret}
		DOClass* GetDOClass() const;
		//{secret}
		ObjDupProtocol* GetAssociatedProtocol();
		//{secret}
		void SetManagerID(unsigned long ulManagerID);
		/*
		Summary: Returns the ID of the manager.
		Note: Expose the method such that the manager ID is a value that makes sense to
		the user.  This is related to session hosting.
		*/
		// {Secret}
		unsigned long GetManagerID() const;

		//Description:  Returns the DOHandle of the station that has this object's Duplication master in its store.
		//Returns:  The DOHandle of the station on which the Duplication master for this duplicated object resides.
		DOHandle GetMasterStation() const;
		// {secret}
		void SetMasterStation(DOHandle hNewMaster, DOHandle hAvailableRouting=INVALID_DOHANDLE); // TODO: Remove the default parameter!
						
		//Description:  Returns the StationID of the station that has this object's Duplication master in its store.
		//Returns:  The StationID of the station on which the Duplication master for this duplicated object resides.
		unsigned long GetMasterID() const {return GetManagerID();}

		/*
		Description: Returns true if the DuplicatedObject is a Duplica.
		Remarks: If the method is called before the object's Duplication role has been
		initialized, the object is neither a Duplication master nor a Duplica.
		Typically, this occurs if the methods IsADuplicationMaster or
		IsADuplica are called in the object constructor.  When the
		initialization of an object depends on its role, it should be done
		via the InitDO system callback, where the role has been defined.
		See Also: Duplication role, IsADuplicationMaster
		*/
		bool IsADuplica() const;
	
		/*
		Description: Returns true if the DuplicatedObject is the Duplication master.
		Remarks: If the method is called before the object's Duplication role has been
		initialized, the object is neither a Duplication master nor a Duplica.
		Typically, this occurs if the methods IsADuplicationMaster or
		IsADuplica are called in the object constructor.  When the
		initialization of an object depends on its role, it should be done
		through the InitDO system callback, where the role has been defined.
		See Also: Duplication role, IsADuplica
		*/
		bool IsADuplicationMaster() const;
		
		/*
		Summary:  Use this method to determin if a duplicated object is an instance of
		a well-known duplicated object class.
		Returns:  true if the DuplicatedObject instance is a member of a class that was declared in the DDF file as 
		well-known, false if otherwise.
		See Also:  DDF File Syntax, DOHandle, WKHandle.
		*/
		bool IsAWellKnownDO() const;

		//{secret}
		bool IsACoreDO() const ;
		//{secret}
		bool IsAUserDO() const {return !IsACoreDO();}
		//{secret}
		bool SetProperty(PropertyCategory ulSBPType, unsigned long ulProperty);
		//{secret}
		bool ChangeProperty(PropertyCategory ulSBPType, unsigned long ulOldProperty, unsigned long ulNewProperty);

/*
Summary: Returns true if the DuplicatedObject has been marked for
deletion.

Note: This method is obsolete. Use DuplicatedObject::DeleteMainRef to delete a
duplicated object.

See Also: DuplicatedObject::DeleteMainRef, MarkForDeletion, DeleteMarkedDOs
*/
		bool IsMarkedForDeletion();
		
/*
Summary: Marks the DuplicatedObject for deletion.

Remarks: The deletion of a DuplicatedObject is a two step process: A
duplication object must first be marked for deletion and then
DeleteMarkedDOs must be called to complete the
deletion of the duplicated objects that have been marked.

This method can only be called on a Duplication master.  When a
Duplication master is deleted, all of its Duplica will also be deleted.

Returns: true if the method is successful, false if it signals an error.
SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA is possible and  SYSTEMERROR_OBJDUP_INVALID_PROPERTY_TRANSITION 
since the object cannot be marked twice for deletion.

Note: This method is obsolete. Use DuplicatedObject::DeleteMainRef to delete a
duplicated object.

See Also: DuplicatedObject::DeleteMainRef
*/
		bool MarkForDeletion();
		// {Secret}
		bool MarkForDeletionSecret(bool bMulticastDeletion);
	
		/*
		Description: Instructs $PRODUCTNAME$ to delete the main reference of the duplicated object.
		Remarks: This method deletes the main reference to the duplicated object held in the 
		duplicated object store. If this was the only reference to the object, the destructor will be 
		called and the object will be deleted with this call. If there are other references to the object
		in existance, e.g. created via the RefTemplate, the destructor will not be called until the
		last reference is released. This method can only be called on the Duplication master of an object.
		Returns:  false if the call signalled an error, true if otherwise. The error
		SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA is possible if the method is called on a Duplica.
		See Also: MainRefIsDeleted, RemoveFromStoreOperation
		*/
		bool DeleteMainRef();
        /*
		Description: Verifies if DeleteMainRef has been called on this object.
		Remarks: If the method DeleteMainRef has been called and therefore, the main reference to 
		the object has been deleted, the destructor will be called on the object when all references 
		to the object have been released, i.e. there are no Refs or iterators that point to the object.
		Returns: true if the method DeleteMainRef has been called on this object and therefore, the 
		main reference to the object has been deleted, false if otherwise.
		See Also: DeleteMainRef
		*/
		bool MainRefIsDeleted() const;

		// {secret}
		bool ConnectOrphanDuplica();
		// {Secret}
		static unsigned long GetRealDOClassID() {return DuplicatedObject_ClassID;}
		
#ifdef FOR_DOC_PURPOSE
		/*
		Summary:  Creates a local instance of a specified doclass.
		Parameters:
		idDOClass: The DOClassID of the duplicated object that is to be created.

		Remarks:  The DDL generated duplicated object classes inherit from the DuplicatedObject class.  
		A specific constructor for each 
		doclass is generated by the DDL compiler into each DOCLASS.  It is not possible to create generic 
		DuplicatedObject instances.  You need to specify the doclass of the instance that you want to create. 
		For example, given that $AvatarORInformationObject$ is declared as a doclass in the DDL file the 
		object can be created in either of the two following ways:
		
		        $AvatarORInformationObject$* pNew$AvatarORInformationObject$=$AvatarORInformationObject$::Create();
		        pNew$AvatarORInformationObject$->Publish();

				DuplicatedObject* pNew$AvatarORInformationObject$=DuplicatedObject::Create(DOCLASSID($AvatarORInformationObject$));
		        pNew$AvatarORInformationObject$->Publish();
		
		*/
		static DuplicatedObject* Create() {
			// This method is provided by specific classes.
			SYSTEMCHECK(false);
			return NULL;
		}
#endif
		static DuplicatedObject* Create(DOClassID idDOClass);

		/*
		Description: Instructs $PRODUCTNAME$ to delete the duplicated objects that are marked for
		deletion.
		Remarks: Duplicated objects are marked for deletion via a call to
		DuplicatedObject::MarkForDeletion.

Note: This method is obsolete. Use DuplicatedObject::DeleteMainRef to delete a duplicated object.

		See Also: DuplicatedObject::MarkForDeletion, DuplicatedObject::DeleteMainRef
		*/
		static void DeleteMarkedDOs();

		/*
		Summary:  Creates a well-known doclass.
		Parameters:
		hWK the name of the global variable that references the well-known instance.  This variable has to be
		the same as that specified in the DDF file.
		
		Remarks:  The DDL generated doclasses inherit from the DuplicatedObject class.  A specific constructor for each 
		doclass is generated by the DDL compiler into each DOCLASS.  It is not possible to create generic 
		DuplicatedObject instances.  You need to specify the doclass of the instance that you want to create.
		For example, given that World is declared as a well-known doclass and the global variable 
		name g_hTheWorld is supplied in the DDF file the well-known object can be created as follows:
		
		        World* pNewWorld=World::CreateWellknown(g_hTheWorld);
		        pNewWorld->Publish();
		
		*/
		static DuplicatedObject* CreateWellKnown(WKHandle& hWK);
		
		/*
		Summary:  Publishes the doclass instance to all stations connected to the session 
		that require the object.
		Remarks:  For example, given that an $AvatarORInformationObject$ is declared as a doclass in the 
		DDL file, it is created and then published as follows:
		
		        $AvatarORInformationObject$* pNew$AvatarORInformationObject$=$AvatarORInformationObject$::Create();
		        pNew$AvatarORInformationObject$->Publish();
		*/
		bool Publish();


		//Group=Templates
		/*
		Summary: The Ref class defined by the duplicated object is used to construct a
		duplicated object reference from a DOHandle and to safely access the
		duplicated object.

		Remarks:  A Ref is a typedef to an appropriate version of the RefTemplate
		template.  All duplicated object subclasses redefine this typedef
		and convert the DOHandle to a reference to the specific subclass of
		duplicated object. 
		
For example, create a Ref to an $AvatarORInformationObject$ with a DOHandle h$AvatarORInformationObject$ as follows:

				$AvatarORInformationObject$::Ref ref$AvatarORInformationObject$(h$AvatarORInformationObject$);
				ref$AvatarORInformationObject$->Render();

		See also: RefTemplate
		*/
		typedef RefTemplate<DuplicatedObject> Ref;

		/*
		Description: Use your duplicated object class name and the SelectionIteratorTemplate 
		class to iterate over duplicated objects.
		Remarks: It is possible to create a SelectionIterator that holds all of the duplicated 
		objects of a certain class on a host as follows: 

				   $AvatarORInformationObject$::SelectionIterator itALL$AvatarORInformationObject$; 

This is implemented via a template. You can find more details about how to use it 
under SelectionIteratorTemplate.     
See Also: Iterators Overview, SelectionIteratorTemplate
		*/ 
		class SelectionIterator : public GenericSelectionIterator {
		public :


			//{secret}
			SelectionIterator();
			//{secret}			
			SelectionIterator(unsigned int uiSelectionType);
			//{secret}			
			virtual ~SelectionIterator() { delete m_pFilter;}	
			//{secret}			
			SelectionIterator(const SelectionIterator& oIt){}
			//{secret}
			DuplicatedObject* operator->() {return (DuplicatedObject*)m_it.GetContent();}
			//{secret}
			DuplicatedObject* GetPtr() {return (DuplicatedObject*)m_it.GetContent();}
		};


	private:
		DOHandle m_dohMyself;
		
	protected:
		RefTemplate<Station> m_refMasterStation;
};



// And a few macros to ease the generation of the code for a specific DuplicateObject...

//Update Macros
//{secret}
#define _DO_DSUpdate(DS,INDEX)		\
	DS.UpdateLoop(this,INDEX)

#define _DO_GeneralDSUpdate(DS,INDEX)	\
	if (pDataset == NULL || pDataset==&##DS) {				\
		_DO_DSUpdate(DS, INDEX);		\
		if (pDataset==&##DS) {			\
			return true;				\
		}								\
	}


//Refresh Macros
#ifdef CPP_EXCEPTION_SUPPORT
#define _DO_DSRefresh(DO, DS)		ConvertErrorToException(DS.Refresh(DO))
#else
#define _DO_DSRefresh(DO, DS)		if(!DS.Refresh(DO)) {return false;}
#endif



#define _DO_GeneralDSRefresh(DO, DS)	\
if (pDataset == NULL || pDataset==&##DS) {				\
	if (!DS.Refresh(DO)) {return false;}	\
    if (pDataset==&##DS) {			\
	    return true;				\
    }								\
}


#define _DO_DSExtract(DS,INDEX)		\
	case INDEX: DS.ExtractFrom(pMsg, false, this); return true; break;
#define _DO_DSExtractFromDiscovery(DS)	\
	DS.ExtractFrom(pMsg, true, this);
#define _DO_DSAddToDiscovery(DS,INDEX)		\
	DS.AddToDiscoveryMessage(this, INDEX, pMsg);

#define _DO_DeclareGeneralMethods(DO)									\
    _DO_##DO(); ~_DO_##DO() {};											\
    bool SpecificUpdate(DataSet *pDataset = NULL);						\
	bool SpecificRefresh(DuplicatedObject *pDO, DataSet *pDataset = NULL);						\
    void SpecificAddDSToDiscoveryMessage(Message* pMsg);				\
    void SpecificExtractDSFromDiscoveryMessage(Message* pMsg);			\
    bool SpecificExtractADataset(Message* pMsg, unsigned char byDatasetIndex);	\
    static void InitDOClass();											\
	void RegisterDatasets();											\
	static unsigned long GetRealDOClassID() {return DOCLASSID(DO);}				\
	static DO* Create();												\
	static DO* CreateWellKnown(WKHandle& hWK);										\
	typedef RefTemplate<DO> Ref;										\
	typedef SelectionIteratorTemplate<DO> SelectionIterator;



#ifdef _DEBUG_CHECK
#define _DO_RegisterDataset(DS) DS.RegisterDOContainer(this);
#else
#define _DO_RegisterDataset(DS)
#endif


#define _DO_ImplementSomeGeneralMethods(DO)							\
	_DO_##DO::_DO_##DO() {SetClassID(DOCLASSID(DO)); RegisterDatasets();}		\
	void _DO_##DO::InitDOClass() {DOClass* pNewClass=fnew _DOC_##DO(); pNewClass->CompleteInitialisation();} \
	DO* _DO_##DO::Create() {return (DO*)UserDOCtrlInterface::GetInstance()->CreateDO(GetRealDOClassID());}	\
	DO* _DO_##DO::CreateWellKnown(WKHandle& hWK) {if (!hWK.IsA(DO::GetRealDOClassID())) {SIGNAL_SYSTEMERROR(SYSTEMERROR_OBJDUP_INVALID_CONSTRUCTION,0); return NULL;} \
	return (DO*)UserDOCtrlInterface::GetInstance()->CreateWellKnownDO(hWK);}

#define _DO_DeclareActionStub(ACTION,ARGS)		\
	bool ACTION##_OnMaster ARGS;				\
    bool ACTION##_OnDuplicas ARGS;				\
	void Callee##ACTION##Stub(Message* pMsg);

#define _DO_DeclareRMCStub(RMC,ARGS)					\
	bool Call##RMC ARGS;								\
	void RMC##Wrapper(LMCContext* pContext);			\
	static void RMC##ReturnStub(RMCContext* pContext);	\

#define _DO_InitStub(ACTION)				\
    ID id=_METHODID(ACTION); Message* pMsg=CreateStubMessage(&id);

#define _DO_RMC_InitCall(RMC)													\
	if (!pContext->PrepareCallMessage(GetHandle(), _METHODID(RMC))) {return false;}		\
	Message* pMsg=pContext->GetCallMessage();

#define _DO_RMC_CompleteCall() return pContext->PerformCall();

#define _DO_RMC_ExtractArg(ARG)	(*pMsg) >> ARG;
#define _DO_RMC_ExtractArgArray(ARG,SIZE) {int i; for (i=0; i<SIZE; i++) {(*pMsg)>>ARG[i];}}
#define _DO_RMC_ExtractStringArg(ARG)	pMsg->ExtractString(ARG);

#define _DO_RMC_InitReturnStub()	Message* pMsg=pContext->GetResponseMessage();  int iArgIndex=0;
#define _DO_RMC_ExtractReturnValue(TYPE,SIZE)	{										\
		TYPE* pReturnLocation=(TYPE*)pContext->GetReturnValuePtr(iArgIndex++);			\
		int i; for (i=0; i<SIZE; i++) {*pMsg >> *pReturnLocation; pReturnLocation++;}	\
  }
#define _DO_RMC_ExtractStringReturn()	pMsg->ExtractString((TCHAR*)pContext->GetReturnValuePtr(iArgIndex++));


#define _DO_RMC_AddArg(ARG)	(*pMsg) << ARG;
#define _DO_RMC_AddArgArray(ARG,SIZE) {int i; for (i=0; i<SIZE; i++) {(*pMsg)<<ARG[i];}}
#define _DO_RMC_AddStringArg(ARG,SIZE)	pMsg->AddDataString(ARG,SIZE);

#define _DO_RMC_AddReturnValue(ARG) pContext->AddReturnValuePtr(ARG);

#define _DO_RMC_InitWrapper() Message* pMsg=pLocalContext->GetCallMessage();
#define _DO_RMC_PrepareReturn() pMsg=pLocalContext->PrepareSuccessMessage();
#define _DO_RMC_CompleteWrapper() 

#define _DO_ExtractStrArg(ARG)	pMsg->ExtractString(ARG);
#define _DO_ExtractArg(ARG,SIZE)	pMsg->Extract(ARG,SIZE);
#define _DO_ExtractObjArg(ARG)	ARG.ExtractFrom(pMsg);
#define _DO_ExtractObjArrayArg(ARG,SIZE)	{int i; for (i=0; i<SIZE; i++) {_DO_ExtractObjArg(ARG[i]);}}

#define _DO_StrArg(ARG,SIZE) pMsg->AddDataString(ARG,SIZE);
#define _DO_Arg(ARG,SIZE) pMsg->AddData(ARG,SIZE);
#define _DO_ObjArg(ARG)	ARG.AddSourceTo(pMsg);
#define _DO_ObjArrayArg(ARG,SIZE)	{int i; for (i=0; i<SIZE; i++) {_DO_ObjArg(ARG[i]);}}

#define _DO_CompleteStub(D) return SendStubMessage(D, pMsg);

#define _DO_DeclareLocationSet(SPACE)	SPACE::LocationSet	m_ls##SPACE;

#define CORE_ROOTDO		DuplicatedObject
#define ROOT_ROOTDO		RootDO
#define GLOBAL_ROOTDO	GlobalDO

#define _DOC_CORE_ROOTDO	DOClass
#define _DOC_ROOT_ROOTDO	_DOC_RootDO
#define _DOC_GLOBAL_ROOTDO	_DOC_GlobalDO

#endif
