// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _FaultToleranceSpaceDDL_H_
#define _FaultToleranceSpaceDDL_H_

#include <ObjDup/ObjDupExport.h>

class FaultToleranceSpace;

class DUPSPACE(FaultToleranceSpace): public DuplicationSpace {
public:
	_DUPSPACE_DeclareGeneralMethods(FaultToleranceSpace);
	_DUPSPACE_NoUserCells();
};

#endif // _FaultToleranceSpaceDDL_H_
