// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _GlobalDODDL_H_
#define _GlobalDODDL_H_

#include <ObjDup/ObjDupExport.h>
#include "RootDO.h"
#include "DOCoreDDF.h"

class GlobalDO;

class DOCLASS(GlobalDO): public RootDO {
public:
	_DO_DeclareGeneralMethods(GlobalDO);

};

class _DOC_GlobalDO: public DOClassTemplate<DOCLASS(GlobalDO), _DOC_RootDO, DOCLASSID(GlobalDO)> {
public:
	_DOC_DeclareGeneralMethods(GlobalDO)
};

#endif // _GlobalDODDL_H_
