// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _IDFactoryDDL_H_
#define _IDFactoryDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "Range.h"
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class IDFactory;

class DOCLASS(IDFactory): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(IDFactory);

	_DO_DeclareRMCStub(GetIDRange, (RMCContext* pCallContext, unsigned long ulNbRequestedID, unsigned long* iFirst, unsigned long* iLast));
	DataSetTemplate<Range>	m_dsFree;
};

class _DOC_IDFactory: public DOClassTemplate<DOCLASS(IDFactory), _DOC_GlobalDO, DOCLASSID(IDFactory)> {
public:
	_DOC_DeclareGeneralMethods(IDFactory)
	_DOC_DeclareRMC(GetIDRange);
};

#endif // _IDFactoryDDL_H_
