// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _LoadBalancingPolicyDDL_H_
#define _LoadBalancingPolicyDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(LoadBalancingPolicy): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(bool,m_bAllStationAreActive);
	_DS_DECLARE_VAR(bool,m_bAutomatic);
	_DS_DECLARE_VAR(double,m_dEquilibriumDeviationThreshold);
	_DS_DECLARE_VAR(double,m_dLoadRatioThreshold);
	_DS_DECLARE_VAR(unsigned long,m_ulEpisodePeriod);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_bAllStationAreActive);
		_DS_ADD_VAR(m_bAutomatic);
		_DS_ADD_VAR(m_dEquilibriumDeviationThreshold);
		_DS_ADD_VAR(m_dLoadRatioThreshold);
		_DS_ADD_VAR(m_ulEpisodePeriod);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_bAllStationAreActive);
		_DS_EXTRACT_VAR(m_bAutomatic);
		_DS_EXTRACT_VAR(m_dEquilibriumDeviationThreshold);
		_DS_EXTRACT_VAR(m_dLoadRatioThreshold);
		_DS_EXTRACT_VAR(m_ulEpisodePeriod);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _LoadBalancingPolicyDDL_H_
