// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _LoadBalancingDomainDDL_H_
#define _LoadBalancingDomainDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "LoadBalancingPolicy.h"
#include "RootDO.h"
#include "DOCoreDDF.h"

class LoadBalancingDomain;

class DOCLASS(LoadBalancingDomain): public RootDO {
public:
	_DO_DeclareGeneralMethods(LoadBalancingDomain);

	DataSetTemplate<LoadBalancingPolicy>	m_dsPolicy;
};

class _DOC_LoadBalancingDomain: public DOClassTemplate<DOCLASS(LoadBalancingDomain), _DOC_RootDO, DOCLASSID(LoadBalancingDomain)> {
public:
	_DOC_DeclareGeneralMethods(LoadBalancingDomain)
};

#endif // _LoadBalancingDomainDDL_H_
