// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _MulticastGroupInfoDDL_H_
#define _MulticastGroupInfoDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(MulticastGroupInfo): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(bool,m_bRoot);
	_DS_DECLARE_VAR(int,m_iContent);
	_DS_DECLARE_VAR(int,m_iLevel);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_bRoot);
		_DS_ADD_VAR(m_iContent);
		_DS_ADD_VAR(m_iLevel);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_bRoot);
		_DS_EXTRACT_VAR(m_iContent);
		_DS_EXTRACT_VAR(m_iLevel);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _MulticastGroupInfoDDL_H_
