// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _MulticastGroupDDL_H_
#define _MulticastGroupDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "MulticastGroupInfo.h"
#include "DOHandleVector.h"
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class MulticastGroup;

class DOCLASS(MulticastGroup): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(MulticastGroup);

	_DO_DeclareActionStub(RemoveMember,(DOHandle hDOToDel));
	_DO_DeclareRMCStub(AddMember, (RMCContext* pCallContext, DOHandle hNewDO));
	DataSetTemplate<MulticastGroupInfo>	m_dsInfo;
	DataSetTemplate<DOHandleVector>	m_dsMembers;
};

class _DOC_MulticastGroup: public DOClassTemplate<DOCLASS(MulticastGroup), _DOC_GlobalDO, DOCLASSID(MulticastGroup)> {
public:
	_DOC_DeclareGeneralMethods(MulticastGroup)
	_DOC_DeclareAction(RemoveMember);
	_DOC_DeclareRMC(AddMember);
};

#endif // _MulticastGroupDDL_H_
