// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _MulticastGroupLoadBalancingDDL_H_
#define _MulticastGroupLoadBalancingDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "LoadBalancingDomain.h"
#include "DOCoreDDF.h"

class MulticastGroupLoadBalancing;

class DOCLASS(MulticastGroupLoadBalancing): public LoadBalancingDomain {
public:
	_DO_DeclareGeneralMethods(MulticastGroupLoadBalancing);

};

class _DOC_MulticastGroupLoadBalancing: public DOClassTemplate<DOCLASS(MulticastGroupLoadBalancing), _DOC_LoadBalancingDomain, DOCLASSID(MulticastGroupLoadBalancing)> {
public:
	_DOC_DeclareGeneralMethods(MulticastGroupLoadBalancing)
};

#endif // _MulticastGroupLoadBalancingDDL_H_
