// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _PromotionRefereeDDL_H_
#define _PromotionRefereeDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class PromotionReferee;

class DOCLASS(PromotionReferee): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(PromotionReferee);

	_DO_DeclareRMCStub(ElectNewMaster, (RMCContext* pCallContext, DOHandle* pResult, DOHandle hObject, DOHandle hFaultyMaster, DOHandle hCalleeStation));
};

class _DOC_PromotionReferee: public DOClassTemplate<DOCLASS(PromotionReferee), _DOC_GlobalDO, DOCLASSID(PromotionReferee)> {
public:
	_DOC_DeclareGeneralMethods(PromotionReferee)
	_DOC_DeclareRMC(ElectNewMaster);
};

#endif // _PromotionRefereeDDL_H_
