// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _RangeDDL_H_
#define _RangeDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(Range): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(unsigned long,m_ulFirst);
	_DS_DECLARE_VAR(unsigned long,m_ulLast);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_ulFirst);
		_DS_ADD_VAR(m_ulLast);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_ulFirst);
		_DS_EXTRACT_VAR(m_ulLast);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _RangeDDL_H_
