// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _RootDODDL_H_
#define _RootDODDL_H_

#include <ObjDup/ObjDupExport.h>
#include "FaultToleranceSpace.h"
#include "SessionSpace.h"
#include "DOCoreDDF.h"

class RootDO;

class DOCLASS(RootDO): public CORE_ROOTDO {
public:
	_DO_DeclareGeneralMethods(RootDO);

	_DO_DeclareActionStub(AddDuplicaLocation,(DOHandle hLocation, bool bUpdateLocationSet, bool bAlwaysSendMessage, DOHandle hAvailableRouting));
	_DO_DeclareActionStub(CreateDuplica,(DOHandle hLocation));
	_DO_DeclareActionStub(RemoveDuplicaLocation,(DOHandle hLocation));
};

class _DOC_RootDO: public DOClassTemplate<DOCLASS(RootDO), _DOC_CORE_ROOTDO, DOCLASSID(RootDO)> {
public:
	_DOC_DeclareGeneralMethods(RootDO)
	_DOC_DeclareAction(AddDuplicaLocation);
	_DOC_DeclareAction(CreateDuplica);
	_DOC_DeclareAction(RemoveDuplicaLocation);
};

#endif // _RootDODDL_H_
