// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SecondaryStationDDL_H_
#define _SecondaryStationDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "SecondaryStationInfo.h"
#include "FaultToleranceSpace.h"
#include "RootDO.h"
#include "DOCoreDDF.h"

class SecondaryStation;

class DOCLASS(SecondaryStation): public RootDO {
public:
	_DO_DeclareGeneralMethods(SecondaryStation);

	DataSetTemplate<SecondaryStationInfo>	m_dsInfo;
};

class _DOC_SecondaryStation: public DOClassTemplate<DOCLASS(SecondaryStation), _DOC_RootDO, DOCLASSID(SecondaryStation)> {
public:
	_DOC_DeclareGeneralMethods(SecondaryStation)
};

#endif // _SecondaryStationDDL_H_
