// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SecondaryStationInfoDDL_H_
#define _SecondaryStationInfoDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(SecondaryStationInfo): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(DOHandle,m_hPrimaryStation);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_OBJECT(m_hPrimaryStation, bDiscovery);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_OBJECT(m_hPrimaryStation);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _SecondaryStationInfoDDL_H_
