// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SessionDDL_H_
#define _SessionDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "SessionInfo.h"
#include "SessionState.h"
#include "UserDefinedState.h"
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class Session;

class DOCLASS(Session): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(Session);

	DataSetTemplate<SessionInfo>	m_dsSessionInfo;
	DataSetTemplate<SessionState>	m_dsSessionState;
	DataSetTemplate<UserDefinedState>	m_dsUserDefinedState;
};

class _DOC_Session: public DOClassTemplate<DOCLASS(Session), _DOC_GlobalDO, DOCLASSID(Session)> {
public:
	_DOC_DeclareGeneralMethods(Session)
};

#endif // _SessionDDL_H_
