// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SessionInfoDDL_H_
#define _SessionInfoDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(SessionInfo): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(DOHandle,m_dohRootMulticastGroup);
	TCHAR	m_szSessionName[128];

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_OBJECT(m_dohRootMulticastGroup, bDiscovery);
		pMsg->AddDataString(m_szSessionName,128);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_OBJECT(m_dohRootMulticastGroup);
		pMsg->ExtractString(m_szSessionName);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _SessionInfoDDL_H_
