// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SessionClockDDL_H_
#define _SessionClockDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "GlobalDO.h"
#include "DOCoreDDF.h"

class SessionClock;

class DOCLASS(SessionClock): public GlobalDO {
public:
	_DO_DeclareGeneralMethods(SessionClock);

};

class _DOC_SessionClock: public DOClassTemplate<DOCLASS(SessionClock), _DOC_GlobalDO, DOCLASSID(SessionClock)> {
public:
	_DOC_DeclareGeneralMethods(SessionClock)
};

#endif // _SessionClockDDL_H_
