// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SessionSpaceDDL_H_
#define _SessionSpaceDDL_H_

#include <ObjDup/ObjDupExport.h>

class SessionSpace;

class DUPSPACE(SessionSpace): public DuplicationSpace {
public:
	_DUPSPACE_DeclareGeneralMethods(SessionSpace);
	_DUPSPACE_NoUserCells();
};

#endif // _SessionSpaceDDL_H_
