// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _SessionStateDDL_H_
#define _SessionStateDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(SessionState): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(unsigned char,m_ucSessionState);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_ucSessionState);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_ucSessionState);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _SessionStateDDL_H_
