// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _StationDDL_H_
#define _StationDDL_H_

#include <ObjDup/ObjDupExport.h>
#include "StationInfo.h"
#include "StationState.h"
#include "FaultToleranceSpace.h"
#include "SessionSpace.h"
#include "RootDO.h"
#include "DOCoreDDF.h"

class Station;

class DOCLASS(Station): public RootDO {
public:
	_DO_DeclareGeneralMethods(Station);

	DataSetTemplate<StationInfo>	m_dsInfo;
	DataSetTemplate<StationState>	m_dsStationState;
};

class _DOC_Station: public DOClassTemplate<DOCLASS(Station), _DOC_RootDO, DOCLASSID(Station)> {
public:
	_DOC_DeclareGeneralMethods(Station)
};

#endif // _StationDDL_H_
