// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _StationInfoDDL_H_
#define _StationInfoDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(StationInfo): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(DOHandle,m_hObserver);
	TCHAR	m_strStationURL1[128];
	TCHAR	m_strStationURL2[128];
	TCHAR	m_strStationURL3[128];
	TCHAR	m_strStationURL4[128];
	TCHAR	m_strStationURL5[128];
	_DS_DECLARE_VAR(unsigned long,m_ulMachineUID);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_OBJECT(m_hObserver, bDiscovery);
		pMsg->AddDataString(m_strStationURL1,128);
		pMsg->AddDataString(m_strStationURL2,128);
		pMsg->AddDataString(m_strStationURL3,128);
		pMsg->AddDataString(m_strStationURL4,128);
		pMsg->AddDataString(m_strStationURL5,128);
		_DS_ADD_VAR(m_ulMachineUID);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_OBJECT(m_hObserver);
		pMsg->ExtractString(m_strStationURL1);
		pMsg->ExtractString(m_strStationURL2);
		pMsg->ExtractString(m_strStationURL3);
		pMsg->ExtractString(m_strStationURL4);
		pMsg->ExtractString(m_strStationURL5);
		_DS_EXTRACT_VAR(m_ulMachineUID);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _StationInfoDDL_H_
