// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _StationStateDDL_H_
#define _StationStateDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(StationState): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(unsigned short,m_usState);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_usState);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_usState);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _StationStateDDL_H_
