// DO NOT MODIFY THIS FILE, IT HAS BEEN GENERATED BY PROKSIM DDL COMPILER

#ifndef _UserDefinedStateDDL_H_
#define _UserDefinedStateDDL_H_

#include <ObjDup/ObjDupExport.h>
class DATASET(UserDefinedState): public DataSet {
public:
	_DS_GENERAL_DECLARATIONS();
	_DS_DECLARE_VAR(int,m_ulUserDefinedState);

	void AddSourceTo(Message *pMsg, Time tTimestamp, bool bDiscovery) {
		_DS_ADD_VAR(m_ulUserDefinedState);
	}

	void ExtractFrom(Message* pMsg) {
		_DS_EXTRACT_VAR(m_ulUserDefinedState);
	}

	_DS_DECLARE_RELIABLE();
	_DS_DECLARE_VARIABLE();
};

#endif // _UserDefinedStateDDL_H_
