//  
//   (c) Copyright 1998-2001, Quazal
//   ALL RIGHTS RESERVED
//  
//  


#ifndef _WKHandle_H_
#define _WKHandle_H_

#include <ObjDup/ObjDupDecl.h>
#include <ObjDup/DOHandle.h>
#include <Utility/IDGenerator.h>
class DuplicatedObjectStore;

// Group=Miscellaneous Classes

/*
Summary:  
A WKHandle refers to a well-known duplicated object.  Whenever a well-known 
duplicated object is declared in the DDF, a global instance of the class
WKHandle is generated by the DDL compiler.  

Remarks:
A WKHandle refers to a well-known duplicated object.  Whenever a well-known 
duplicated object is declared in the DDF, a global variable of
the WKHandle type is generated by the DDL compiler.  The WKHandle
class instances inherit from the DOHandle class.

See Also: DOHandle
*/
class WKHandle: public DOHandle {
	// Group=
	public:

		/*Summary:  Instances of WKHandle should not be directly instantiated, but
		instead should be declared in the DDF file.  
		
		See Also:  DDF File Syntax, DDL File Syntax.
		*/
		WKHandle();
		
		/*
		Summary: Destroys the WKHandle. 

		Remarks: A WKHandle should never be directly destroyed. They are automatically destroyed
		when the duplicated object to which they have a handle is destroyed.

		See Also: DuplicatedObject
		*/
		~WKHandle();

		// {Secret}
		void Init(DOClassID idDOClass);
		// {Secret}
		static void Cleanup();

		// Error checking methods...
		// {Secret}
		static bool AllInDOS(DuplicatedObjectStore* pDOS);
		// {Secret}
		static bool AtLeastOneCreated();
		// {Secret}
		void Instanciated() {m_bInstanciated=true;}
		// {Secret}
		bool IsInstanciated() {return m_bInstanciated;}

		// {Secret}
		static bool IsAWKHandle(DOHandle hDO);
		
	private:
		bool m_bInitialized;
		bool m_bInstanciated;
		WKHandle* m_phNext;

		static WKHandle* s_phFirst;
		static IDGenerator s_oID;
};

#endif
