#include <Plugins/Core/Buffer.h>

typedef unsigned char   undefined;

typedef unsigned char    bool;
typedef unsigned int    dword;
typedef unsigned char    uchar;
typedef unsigned int    uint;
typedef unsigned long    ulong;
typedef unsigned int    undefined4;
typedef unsigned short    ushort;
typedef unsigned short    word;
typedef struct CoffFileHeader CoffFileHeader, *PCoffFileHeader;

struct CoffFileHeader {
    word f_magic;
    word f_nscns;
    dword f_timdat;
    dword f_symptr;
    dword f_nsyms;
    word f_opthdr;
    word f_flags;
};

typedef struct CoffSectionHeader CoffSectionHeader, *PCoffSectionHeader;

struct CoffSectionHeader {
    char s_name[8];
    dword s_paddr;
    dword s_vaddr;
    dword s_size;
    dword s_scnptr;
    dword s_relptr;
    dword s_lnnoptr;
    word s_nreloc;
    word s_nlnno;
    dword s_flags;
};

#define INVALID_CONTEXT_ID 0

#define DEFAULT_SOURCE_UNDEFINED 65535

#define VARIABLE_SOURCE_FILE 4

#define VARIABLE_SOURCE_ENVIRONMENT 3

#define VARIABLE_SOURCE_REGISTRY 2

#define VARIABLE_SOURCE_DEFAULT 1

#define VARIABLE_SOURCE_NONE 0

#define INFINITE_BANDWIDTH 4294967295

#define FIRST_USER_DOCLASSID 15

#define Station_ClassID 4

#define IDFactory_ClassID 10

#define GlobalDO_ClassID 3

#define Session_ClassID 7

#define DefaultCell_ClassID 9

#define SessionClock_ClassID 6

#define MulticastGroupLoadBalancing_ClassID 14

#define RootDO_ClassID 2

#define PromotionReferee_ClassID 11

#define SecondaryStation_ClassID 5

#define DOLoadBalancing_ClassID 13

#define LoadBalancingDomain_ClassID 12

#define MulticastGroup_ClassID 8

#define PERF_TRANSPORT_PACKETS_SENT 2

#define PERF_TRANSPORT_HIGHEST_ID 4

#define PERF_TRANSPORT_PACKETS_LOST 4

#define PERF_TRANSPORT_PACKETS_RECV 3

#define PERF_TRANSPORT_BPS_RECV 1

#define PERF_TRANSPORT_BPS_SENT 0

#define PRIORITY_NORMAL 1

#define PRIORITY_HIGH 2

#define PRIORITY_LOW 0

#define IT_MOVE_END 1

#define IT_MOVE_NEXT 2

#define IT_MOVE_START 0

#define SYSTEM_STATION_MESSAGE 1

#define USER_STATION_MESSAGE 0

#define DISCARD_VALUE 0

#define DELAY_VALUE 6

#define INSERT_VALUE_AT_THE_END_x2 4

#define INSERT_VALUE_AT_THE_END 3

#define INSERT_VALUE_AT_THE_END_x3 5

#define INSERT_VALUE_BEFORE_SECOND 1

#define UNKNOWN_POSITION 255

#define INSERT_VALUE_BEFORE_THIRD 2

#define MAX_NB_THREADS 256

#define TRANSPORT_SPECIFIC_OPTIONS 256

#define TRANSPORT_OPTION_MTU 1

#define TRANSPORT_OPTION_WELLKNOWN_INFO 2

#define ANGLE_IN_RADIANS 1

#define ANGLE_IN_DEGREES 2

#define TRANSPORT_ERROR_CANNOT_INITIALIZE 2

#define TRANSPORT_ERROR_DUPLICATE_END_POINT 23

#define TRANSPORT_ERROR_CONNECTION_RESET 21

#define TRANSPORT_ERROR 1

#define TRANSPORT_ERROR_INVALID_MESSAGE 10

#define TRANSPORT_ERROR_NOT_CONNECTED 5

#define TRANSPORT_ERROR_INVALID_TRANSPORT_TYPE 15

#define TRANSPORT_ERROR_TIMEOUT 17

#define TRANSPORT_SUCCESS 0

#define TRANSPORT_ERROR_CONNECTED 6

#define TRANSPORT_ERROR_INVALID_HANDLE 7

#define TRANSPORT_ERROR_NOT_INITIALIZED 19

#define TRANSPORT_ERROR_INVALID_PACKET 11

#define TRANSPORT_ERROR_INVALID_BUFFER 9

#define TRANSPORT_ERROR_KEY_NOT_FOUND 14

#define TRANSPORT_ERROR_COULD_NOT_CONNECT 4

#define TRANSPORT_ERROR_BUFFER_OVERFLOW 8

#define TRANSPORT_ERROR_NOT_READY 16

#define TRANSPORT_ERROR_INTERFACE_NOT_FOUND 22

#define TRANSPORT_ERROR_INDEX_OUT_OF_RANGE 13

#define TRANSPORT_ERROR_INVALID_URL 12

#define TRANSPORT_ERROR_IO_ERROR 3

#define TRANSPORT_ERROR_EVENT_HANDLER_REGISTERED 18

#define TRANSPORT_ERROR_INVALID_PARAMETER 20

#define MARKED_FOR_LOCAL_DELETION 1

#define MARKED_FOR_DELETION 0

#define SYSTEM_STATE_TERMINATING 3

#define SYSTEM_STATE_RUNNING 1

#define SYSTEM_STATE_INITIALIZING 0

#define SYSTEM_STATE_PAUSED 2

#define ENCRYPTION_ERROR_CANNOT_CRYPT 2

#define ENCRYPTION_ERROR_INVALID_PARAM 3

#define ENCRYPTION_ERROR_NOT_SUPPORTED 4

#define ENCRYPTION_ERROR 1

#define ENCRYPTION_SUCCESS 0

#define LARGESTID 4194302

#define GET_RANGE_TIMEOUT 10000

#define DEFAULT_REQUESTED_RANGE_SIZE 16

#define MAXID -2

#define PRODUCT_KEY_MAX_SIZE 64

#define DEFAULT_MAXIMUM_UPDATE_DELAY 2000

#define NO_MAXIMUM_UPDATE_DELAY 0

#define INFINITE_SPIN 4294967295

#define OPERATIONS 0

#define CONTENT 1

#define CHRONO_IS_PAUSED 1

#define CHRONO_IS_STARTED 0

#define CHRONO_IS_STOPPED 2

#define INVALID_TIME_INTERVAL -1

#define NETZ_PRODUCTID 1

#define CORE_PRODUCTID 0

#define ETERNA_PRODUCTID 3

#define TSIS_PRODUCTID 2

#define INVALID_CONTEXT 65535

#define DEFAULT_CONTEXT 0

#define STATION_EVENT_FAILURE 2

#define INVALID_STATION_ID 4294967295

#define STATION_EVENT_JOIN 0

#define STATION_EVENT_QUIT 1

#define LAST_GAME_EVENT_ID 3

#define STATION_EVENT_PROMOTION 3

#define RING_BUFFER_SIZE 4096

#define MATCH_LENGTH_LIMIT 18

typedef struct PacketIn PacketIn, *PPacketIn;

struct PacketIn { // PlaceHolder Structure
};

typedef struct Buffer Buffer, *PBuffer;

typedef struct Packet Packet, *PPacket;

struct Packet { // PlaceHolder Structure
};

#define MATCH_PUBLISHER_DUPLICA 2

#define MATCH_PUBLISHER_MASTER 1

#define MATCH_PS_DUPLICA 32

#define MATCH_CELL_DUPLICA 128

#define MATCH_CELL_MASTER 64

#define MATCH_PS_MASTER 16

#define MATCH_SUBSCRIBER_DUPLICA 8

#define MATCH_SUBSCRIBER_MASTER 4

#define PERF_FREQUENCY_MIN 3

#define PERF_FREQUENCY_AVERAGE 2

#define PERF_FREQUENCY_LAST 1

#define PERF_FREQUENCY_MAX 4

#define PERF_COUNT_TOTAL 5

#define DUPLICATION_MASTER 0

#define DUPLICA 1

#define DuplicatedObject_ClassID 1

#define FIRST_CORE_DOCLASSID 2

#define INVALID_CLASSID 0

#define TRANSPORT_CAPS_PERF_COUNTERS 4

#define TRANSPORT_CAPS_GROUPING 5

#define TRANSPORT_CAPS_ARBITRARY_LISTEN_SUPPORTED 7

#define TRANSPORT_CAPS_IP_BASED 1

#define TRANSPORT_CAPS_DEVICE_EMULATION 3

#define TRANSPORT_CAPS_BROADCAST 2

#define TRANSPORT_CAPS_WELLKNOWN_LISTEN_SUPPORTED 6

#define D_TRACE_LOCK 2097152

#define TRACE_LOADBALANCING 128

#define CONSOLE_DEVICE 1

#define TRACE_OPERATION 16

#define D_TRACE_WAIT 4194304

#define FILE_DEVICE 3

#define D_TRACE_TRANSPORT_PROTO 134217728

#define TRACE_USER 2048

#define D_TRACE_USAGELOG 8388608

#define D_TRACE_MIGRATION 262144

#define TRACE_PLUGIN 1024

#define TRACE_TEARDOWN 4096

#define TRACE_DOPROTOCOL 512

#define D_TRACE_TRANSPORT 100663296

#define D_TRACE_PROFILING 536870912

#define D_TRACE_DOPROPERTY 131072

#define DEBUGOUTPUT_DEVICE 2

#define D_TRACE_REFCOUNT 524288

#define D_TRACE_TREE_CREATION 268435456

#define TRACE_PHBDR 256

#define D_TRACE_TIME_SYNC 16777216

#define TRACE_SYSTEMCHECK 1

#define TRACE_ALWAYS 1

#define D_TRACE_THREADS 1048576

#define NO_DEVICE 0

#define TRACE_ALL 8189

#define D_TRACE_TEST 1073741824

#define TRACE_DUPSPACE 64

#define TRACE_FAULT 32

#define D_TRACE_TRANSPORT_CONNECT 33554432

#define TRACE_NEVER 0

#define D_TRACE_DEBUG 65536

#define D_TRACE_TRANSPORT_MSG 67108864

#define TRACE_UPDATE 8

#define D_TRACE_TECHSUPPORT 2147483648

#define TRACE_INIT 4

#define D_TRACE_ALL 4294967295

#define REQUEST_LOCAL_LOAD_INFO_REPORT 3

#define DEFAULT_EPISODE_PERIOD 20000

#define PARTICIPATE 5

#define SCHEDULE_LOAD_BALANCING_EPISODE 4

#define CANCEL_PARTICIPATION 6

#define GET_REMOTE_LOAD_INFO_TIMEOUT 5000

#define REQUEST_LOAD_TRANSFER 2

#define LOCAL_LOAD_INFO_REPORT 1

#define TRANSFER_LOAD_TIMEOUT 5000

#define MIGRATION_REASON_USER_REQUEST 3

#define MIGRATION_REASON_LEAVING_GAME 0

#define MIGRATION_REASON_LOAD_BALANCING 1

#define MIGRATION_REASON_LEAVING_SESSION 0

#define MIGRATION_REASON_LEAVING_CLUSTER 0

#define MIGRATION_REASON_TWO_MASTERS 65538

#define FORCED_MIGRATION 65536

#define CONTINUITY_BREAK_STOP 2

#define CONTINUITY_BREAK_SUDDEN_CHANGE 3

#define CONTINUITY_BREAK_SUDDEN_CHANGE_2ND_UPDATE 4

#define CONTINUITY_BREAK_SUDDEN_CHANGE_LAST_UPDATE 5

#define CONTINUITY_BREAK_TELEPORT 1

#define CONTINUITY_BREAK_UPDATED_MODEL 128

#define CONTINUITY_BREAK_HIGHEST_VALUE 5

#define CONTINUITY_BREAK_NONE 0

#define CONTINUITY_BREAK_INITIALISATION 1

#define MSG_PRIO_HIGH 2

#define MSG_PRIO_LOW 4

#define MSG_RELIABLE 1

#define MSG_PRIO_NORMAL 0

#define MSG_UNRELIABLE 0

#define INVALID_DUPSPACEID 0

#define SYSTEMERROR_GEN_OBJ_NOT_INIT 3758096392

#define SYSTEMERROR_GEN_DEADLOCK_DETECTED 3758096404

#define SYSTEMERROR_GEN_ASSERTION_FAILED 3758096403

#define SYSTEMERROR_OBJDUP_INVALID_PARAMETER 3758292997

#define SYSTEMERROR_GEN_NOT_ENOUGH_MEM 3758096384

#define SYSTEMERROR_OBJDUP_INVALID_ON_MASTER 3758292993

#define SYSTEMERROR_GEN_MULTIPLE_INSTANCES 3758096399

#define SUBSYSTEM_DC 2

#define NUMBER_OF_SUBSYSTEMS 4

#define SYSTEMERROR_DC_CLUSTER_JOIN_FAILED 3758293010

#define SYSTEMERROR_GEN_OUT_OF_ID 2684354570

#define SYSTEMERROR_GEN_WIN32_ERROR 3758096386

#define SEV_WARNING 2

#define SYSTEMERROR_GEN_INTERNAL 2684354571

#define SYSTEMERROR_OBJDUP_CANNOT_EMIGRATE 3758292998

#define SYSTEMERROR_DC_INVALID_STATE_TRANSITION 3758293015

#define SYSTEMERROR_OBJDUP_WKHANDLE_WERE_CREATED 3758293003

#define SYSTEMERROR_OBJDUP_INVALID_CONSTRUCTION 3758292999

#define SYSTEMERROR_OBJDUP_ALREADY_PUBLISHED 3758293000

#define SYSTEMERROR_OBJDUP_DO_NOT_FOUND 2684551172

#define SYSTEMERROR_DC_NOT_CLUSTER_MASTER 3758293014

#define SYSTEMERROR_OBJDUP_INVALID_ON_DUPLICA 3758292992

#define SEV_INFORMATIONAL 1

#define SYSTEMERROR_GEN_IO_ERROR 3758096407

#define SYSTEMERROR_GEN_INVALID_PARAMETER 3758096406

#define SYSTEMERROR_OBJDUP_INVALID_PROPERTY_TRANSITION 3758292994

#define SYSTEMERROR_DC_CLUSTER_REDEFINITION 3758293008

#define SYSTEMERROR_MISSING_DATASET_CALLBACK 3758293001

#define SYSTEMERROR_OBJDUP_UNDEFINED_CALLBACK 2684551171

#define SUBSYSTEM_NONE 16

#define SYSTEMERROR_GEN_INDEX_OOB 3758096387

#define SYSTEMERROR_GEN_DUPLICATED_KEY 2684354564

#define SYSTEMERROR_GEN_CHILDPROCESS_FAILED 2684354573

#define SYSTEMERROR_DC_CLUSTER_NOT_INITIALIZED 3758293013

#define SYSTEMERROR_GEN_ILLEGAL_ACCESS 3758096385

#define SYSTEMERROR_OBJDUP_MISMATCHED_DOCLASS 3758293004

#define SYSTEMERROR_OBJDUP_WKHANDLE_EXISTS 3758293005

#define SYSTEMERROR_OBJDUP_STATION_NOT_FOUND 2684551183

#define SYSTEMERROR_GEN_NOT_INITIALIZED 3758096405

#define SYSTEMERROR_GEN_EXPIRED 3758096401

#define SYSTEMERROR_GEN_ITEM_NOT_DELETED 2684354565

#define SYSTEMERROR_GEN_NOT_IMPLEMENTED 3758096393

#define SYSTEMERROR_GEN_TIMEOUT 3758096396

#define SYSTEMERROR_GEN_INVALID_OPERATION 3758096398

#define SYSTEMERROR_DC_MISMATCHED_BARRIER_ID 3758293011

#define SUBSYSTEM_OBJDUP 3

#define SYSTEMERROR_OBJDUP_CANNOT_PUBLISH 3758293006

#define SEV_SUCCESS 0

#define SYSTEMERROR_DC_CLUSTER_JOIN_DENIED 3758293009

#define SYSTEMERROR_FACADE_NOT_INITIALIZED 3759144960

#define SYSTEMERROR_OBJDUP_TRANSPORT_NOT_FOUND 3758293017

#define SYSTEMERROR_GEN_ITEM_NOT_FOUND 2684354566

#define SEV_ERROR 3

#define SYSTEMERROR_GEN_END_OF_COLLECTION 2684354567

#define SYSTEMERROR_DC_CLUSTER_ALREADY_INITIALIZED 3758293016

#define SUBSYSTEM_GENERAL 0

#define SYSTEMERROR_GEN_INVALID_PRODUCT_KEY 3758096408

#define SYSTEMERROR_DC_BARRIER_TIMEOUT 1610809364

#define SYSTEMERROR_GEN_OUT_OF_RANGE 3758096402

#define SYSTEMERROR_OBJDUP_WKHANDLE_NOT_INITIALIZED 3758293002

#define SUBSYSTEM_NETWORK 1

#define SYSTEMERROR_GEN_MULTIPLE_EXCEPTION_HANDLER 3758096400

#define MAX_NB_CLASSID 1024

#define OBJECTID_BITS 22

#define MAX_NB_WELLKNOWNDO 256

#define OBJECTID_MASK 4194303

#define CLASSID_MASK -4194304

#define CLASSID_BITS 10

#define MAX_NB_OBJECTID 4194304

#define RELEASE_TARGET 2

#define CUSTOM_TARGET 3

#define PLUGIN_MANAGER_VERSION 1

#define COMPRESSION_PLUGIN_TYPE 2

#define DEBUG_TARGET 1

#define TRANSPORT_PLUGIN_TYPE 1

#define UNICODE_STRING_FORMAT 1

#define ANSI_STRING_FORMAT 2

#define ENCRYPTION_PLUGIN_TYPE 3

#define PRUDP_KEEPALIVETIMEOUT 260

#define PRUDP_TRAPICMPERRORS 258

#define PRUDP_WINDOW_SIZE 262

#define PRUDP_MAXSILENCETIME 259

#define PRUDP_MAXRETRANSMISSION 257

#define PRUDP_BROADCAST_EVERYWHERE 256

#define PRUDP_TIMESLICE 261

#define DATASET_OP_REGISTER 0

#define DATASET_OP_UNREGISTER 1

#define UNDEFINED_VARIABLE 65535

#define SESSION_ROLE_UNDEFINED 0

#define SESSION_ROLE_MASTER 1

#define SESSION_ROLE_DUPLICA 2

#define WAIT_INFINITE 4294967295

#define OTHER_FEATURE3 8

#define OTHER_FEATURE4 16

#define OTHER_FEATURE5 32

#define STATIONS_ALWAYS_GLOBAL 1

#define OTHER_FEATURE1 2

#define OTHER_FEATURE2 4

#define UNASSIGNED_METHODID 0

#define NET_FAULT_CONNRESET 1

#define NET_FAULT_UNREACHABLE 3

#define NET_FAULT_TIMEOUT 2

#define VERSION_NUMBER_3 550

#define VERSION_NUMBER_4 10

#define MAX_CHILDRENPROCESSES 64

#define GROUP_CONTENT 1

#define STATION_CONTENT 0

#define TOTAL_INSTANCE_TYPE 8

#define IC_TYPE_DOS 4

#define INVALID_INSTANCE 4294967295

#define IC_TYPE_CORE_DO_CTRL_INTERFACE 3

#define IC_TYPE_APP_CTRL_INTERFACE 1

#define IC_TYPE_FACADE 0

#define IC_TYPE_DUPLICATION_SPACE_TABLE 6

#define IC_TYPE_USER_DO_CTRL_INTERFACE 2

#define IC_TYPE_CLUSTER_CLOCK 7

#define IC_TYPE_LOAD_BALANCING_ACTIVITY 5

#define ROUTER_BUFFER_SIZE_DEFAULT 10000000

#define UPDATE_CHANNEL_NUMBER 0

#define NODE_ID_UNDEFINED 0

#define PROPERTY_UNKNOWN -1

#define PROPERTY_NONE -2

#define PERF_DATASET_HIGHEST_ID 2

#define PERF_DATASET_UPDATE_MULTICASTS 1

#define PERF_DATASET_UPDATES 0

#define PERF_DATASET_UPDATE_MESSAGES 2

#define LOADARRAY_SIZE 1

#define LOAD_STATUS_LOW 1

#define LOAD_STATUS_HIGH 3

#define LOAD_STATUS_FAIR 2

#define LOADCAT_DUPLICATIONMASTERS 0

#define LOAD_STATUS_UNKNOWN 0

#define NO_LIMIT 4294967295

#define MULTICAST 1

#define BROADCAST 0

#define FILE_OPEN_EXISTING 2

#define FILE_CREATE_ALWAYS 1

#define FILE_OPEN_ALWAYS 4

#define DEFAULT_BUF_SIZE 4096



undefined LAB_00002513;
pointer `vftable';
undefined __except_list;

// public: __thiscall PacketIn::PacketIn(void)

PacketIn * __thiscall PacketIn::PacketIn(PacketIn *this)

{
  Buffer *pBVar1;
  int unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  int local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &_L1150;
  local_c = *(undefined4 *)(&__except_list + unaff_FS_OFFSET);
  *(undefined4 **)(&__except_list + unaff_FS_OFFSET) = &local_c;
  Packet::Packet((Packet *)this);
  local_4 = 0;
  *(undefined ***)this = &_vftable_;
  pBVar1 = operator_new(0x20);
  local_4._0_1_ = 1;
  if (pBVar1 == (Buffer *)0x0) {
    pBVar1 = (Buffer *)0x0;
  }
  else {
    pBVar1 = (Buffer *)Buffer::Buffer(pBVar1,0x1000);
  }
  local_4 = (uint)local_4._1_3_ << 8;
  Packet::SetPayload((Packet *)this,pBVar1);
  *(undefined4 *)(&__except_list + unaff_FS_OFFSET) = local_c;
  return this;
}



// public: virtual void * __thiscall PacketIn::`scalar deleting destructor'(unsigned int)

void * __thiscall PacketIn::_scalar_deleting_destructor_(PacketIn *this,uint param_1)

{
  ~PacketIn(this);
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}



// public: virtual __thiscall PacketIn::~PacketIn(void)

void __thiscall PacketIn::~PacketIn(PacketIn *this)

{
  Packet::~Packet((Packet *)this);
  return;
}



// public: bool __thiscall PacketIn::Unpack(class Buffer *)

bool __thiscall PacketIn::Unpack(PacketIn *this,Buffer *param_1)

{
  bool bVar1;
  ushort uVar2;
  ulong uVar3;
  Buffer *pBVar4;
  uchar *puVar5;
  ulong uVar6;
  
  uVar3 = Buffer::GetContentSize(param_1);
  if (uVar3 != 0) {
    bVar1 = Buffer::ValidateAndRetrieveChecksum(param_1);
    if (bVar1) {
      bVar1 = Buffer::CopyContent(param_1,this + 0xc,8,0);
      if (bVar1) {
        pBVar4 = Packet::GetPayload((Packet *)this);
        Buffer::Clear(pBVar4);
        uVar2 = Packet::GetSize((Packet *)this);
        uVar3 = Buffer::GetContentSize(param_1);
        if (uVar3 == uVar2) {
          uVar6 = 0xffffffff;
          uVar3 = Buffer::GetContentSize(param_1);
          uVar3 = uVar3 - 8;
          puVar5 = Buffer::GetContentPtr(param_1);
          puVar5 = puVar5 + 8;
          pBVar4 = Packet::GetPayload((Packet *)this);
          bVar1 = Buffer::AppendData(pBVar4,puVar5,uVar3,uVar6);
          return bVar1;
        }
      }
    }
  }
  return false;
}


